server:
  port: 9527
spring:
  application:
    name: cloud-payment-service

eureka:
  client:
    #false表示不向服务中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
       #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: payment8001 #主机名
    prefer-ip-address: true # 访问路径可以显示IP地址